export default [
    {
        filter:"Electrical",
        image:"Images/dp.jpg"
    },
    {
        filter:"",
        image:"Images/dp.jpg"
    },
    {
        image:"Images/dp.jpg"
    },
    {
        image:"Images/dp.jpg"
    },

    {
        image:"Images/banner.jpg"
    },
    {
        image:"Images/dp.jpg"
    },
    {
        image:"Images/dp.jpg"
    },
    {
        image:"Images/dp.jpg"
    },
    {
        image:"Images/contact-head.jpeg"
    },
    {
        image:"Images/dp.jpg"
    },
    {
        image:"Images/dp.jpg"
    },
    {
        image:"Images/dp.jpg"
    },
    {
        image:"Images/dp.jpg"
    },
    {
        image:"Images/dp.jpg"
    },
    {
        image:"Images/dp.jpg"
    }

]